### ISSUE TITLE
extract_kraken_reads.py throwing a error

### ISSUE THREAD

**Issue by bhanu166** [jenniferlu717/KrakenTools#1]
Hi Thanks for the tool. I tried testing it today and it is giving me this error. I used kraken file from the kraken2 tool and paired end files which i used as an input. In step 1 it is able to find the reads ID assigned to the taxa. But in step 2 the reads ids are not being found in the fastq files.

![Screen Shot 2019-08-23 at 10 43 19 AM](https://user-images.githubusercontent.com/28985956/63601329-3580ab00-c593-11e9-86ce-b388dbc042e1.png)

**Comment by jenniferlu717** [comment]
What are the first lines for the kraken file and one of the read files?

**Comment by bhanu166** [comment]
C       A00387:131:GW190809232nd:1:1101:1027:3302       1827469 150|150 A:2 0:50 1827469:1 0:63 |:| 0:116
C       A00387:131:GW190809232nd:1:1101:1027:9471       1696    150|150 A:2 0:106 85006:2 1696:5 0:1 |:| 0:54 1873:2 0:5 1877:3 0:52
C       A00387:131:GW190809232nd:1:1101:1027:11099      1136497 150|150 A:2 0:114 |:| 0:16 1136497:1 0:5 1696:5 0:1 1696:7 0:81 here are the first lines from kraken file.


@A00387:131:GW190809232nd:1:1101:1027:3302/1
ANCATCAACAGGTCGCGATAGGGCGTTCCCACCTGAAGATAGGGGCCCATTTCCGGGTTCACCTCGGCATAGCGTGCGTTCCACAGCACCAGCCGGTCGTTGAGATCGAAGAAGCTCAGCCCGTCCGGCATGGCGTCCACCGCCTCGCGG
+
,#::FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:FFFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFFFFF:FFFF,FFFFFFFFFF,FF,F:,FFFFF,FFF::FFFF:FFFFFFFFFFFFF:F:F
@A00387:131:GW190809232nd:1:1101:1027:9471/1
ANCCTGACCGGCGCCCAGATCGTCGCGCTGGGCAACCGGACCTCCGGTGTCATGGGCGACGAGGCGGTGCGGGAGAAGGTGAGCGAGCAGGCGAAGATCGCCGGAGAGGACATCTGGCCGATGCCGATCCCCGAGGAGATGCTCGCAGGC
First lines from input read files.

**Comment by jenniferlu717** [comment]
Sorry it took me so long. I finally fixed it to allow for the \1/\2 in the FASTA record id.
