### ISSUE TITLE
KrakenTools using huge amounts of RAM

### ISSUE THREAD

**Issue by maxmaronna** [jenniferlu717/KrakenTools#10]
Hello,
I am trying to create "decontaminated" fastaq files using Kraken2 and KrakenTools.
After I created the DB and I classified my reads using kraken2, I am trying to use KrakenTools. My problem is I cannot finish my job: KrakenTools is using a huge amount of memory (+125GB) even for small/medium datasets to be decontaminated (~50 millions reads each for paired end)...any idea about how to avoid this issue?
Thanks in advance.

**Comment by jenniferlu717** [comment]
Definitely my own fault, I haven't tested the script for RAM usage. Are you trying to extract FASTQ or FASTA files? and for paired, are you trying to get two different files or one single file? This will help me fix the script to use less memory.

**Comment by maxmaronna** [comment]
Hi Jennifer, thanks for your support :)
I am extracting FASTQ files (and I would like to have as output FASTQ too). Also, I am trying to get two different files (paired R1, paired R2). If you want extra details, my email is maxmaronna@gmail.com
Thanks a lot for your help!

**Comment by jenniferlu717** [comment]
Should be fixed now. I had to remove the ability for paired reads to be combined into a single output file, but users can just get the paired reads in two separate output files. I might make another script that can combine them after. 

Anyway, RAM wise, the reads are no longer saved in memory so the script should use far less RAM (for my test, it went down from 15GB to 700Mb). RAM should still be a function of the number of reads being extracted. Let me know if you continue to have problems.

**Comment by maxmaronna** [comment]
Hi Jennifer, 
update version is now working with no RAM issue, thanks a lot :)
Just a final question/request: is there a way to preserve reads´ original names in the new fastq files?
Thanks in advance,
max

**Comment by jenniferlu717** [comment]
The reads' original names should be preserved? My script no longer changes the names.

**Comment by maxmaronna** [comment]
I jennifer,
I really prefer to keep the original names (I have to combine several libs, etc). Also, seqkit found reads´ problems in one of the paired-end fq "decontaminated" files using previous kraken-tools version (I will double check everything with your last version; I will inform you asap)
Thanks for all your help :)

**Comment by maxmaronna** [comment]
Hi Jennifer,
KrakenTools is working great. I have a final question: any future option to use as a parallel script (--threads option)?
All the best
max

**Comment by jenniferlu717** [comment]
Maybe. Right now the scripts are all written in python, which isn't really parallel-lizable (not like C/C++ is) so it would require me porting the script to C/C++. If the script ends up taking a huge amount of time, I may convert them. 

How long does it take for you @maxmaronna ? Just so I can get an idea of the user req.

**Comment by maxmaronna** [comment]
Hi Jennifer, sorry I didn´t see this last message.

It took at least 6 hours for a medium-size dataset (~150 million reads -each Rxxx), being filtered ~95% of the original reads...

All the best
max

**Comment by jenniferlu717** [comment]
Ah yeah ill try to make a parallelized version

**Comment by maxmaronna** [comment]
Great, thanks a lot Jennifer!

**Comment by tseemann** [comment]
Can it be parallelized with just python worker threads?
ie. `multiprocessing` 
Or by breaking the input data up and using GNU `parallel` ?

**Comment by jenniferlu717** [comment]
python doesn't parallelize super well, but I could try. GNU parallel is easiest but I haven't worked with it a lot. I dont have time to look at this today but maybe this weekend.

**Comment by tseemann** [comment]
It depends on what sort of parallelization is needed.

**Comment by alirizaaribas-ibg** [comment]
> Can it be parallelized with just python worker threads?
> ie. `multiprocessing`
> Or by breaking the input data up and using GNU `parallel` ?

It is better to prefer HPC compatible multiprocessing with openmp or mpi. How can it be decided?
