### ISSUE TITLE
Bioconda package / release

### ISSUE THREAD

**Issue by apeltzer** [jenniferlu717/KrakenTools#12]
Going down the same road as #11 - is there a plan to have this released as a versionized package on GitHub/Bioconda/PyPi? 

I'm currently writing a MultiQC module and it would be extremely helpful to be able to a.) import this as a set of scripts to create appropriate tables and then b.) get these for visualization into MultiQC.

https://github.com/ewels/MultiQC/issues/121 

That would be much easier if you could (at a minimum) create an ideally versionized script release here on Github and/or provide a pip3 installable #11 so we can get this to Bioconda. 

I would be happy to help of course if you need any help on this :-)

**Comment by pvanheus** [comment]
There is a bioconda [recipe](https://github.com/bioconda/bioconda-recipes/pull/21634) in progress.

**Comment by apeltzer** [comment]
Nice @pvanheus !
