### ISSUE TITLE
Convert Kraken output to Megan

### ISSUE THREAD

**Issue by keenhl** [jenniferlu717/KrakenTools#14]
Hi all,

Is there any way to convert Kraken2 output into a format that can be loaded into the Megan program (version 6)?  I'm new using Kraken2, and Megan, so I apologize in advance if this is a nonsensical question.

Thanks,

**Comment by jenniferlu717** [comment]
I do not believe so. I think Megan takes in alignments from BLAST, but Kraken does not align to specific genomes.

**Comment by keenhl** [comment]
Thank you for the information.  I should mention that I have found Krona Tools to be very useful for viewing the Kraken results.   

Thanks again
