### ISSUE TITLE
No read IDs found

### ISSUE THREAD

**Issue by Maryamtarazkar** [jenniferlu717/KrakenTools#16]
Hi, 
I am trying to use "extract_kraken_reads.py" script to extract the reads related to particular species. From kraken report it is shown that there are 465 reads related to the species I am interested in. 
I applied following command but the 
python extract_kraken_reads.py -k 107C_out.kraken -s 107C_seq.file -o extract_107C.fastq -t 813 &

but eventually, no read ID is found . Here is my output; 

PROGRAM START TIME: 08-07-2020 01:38:50
        1 taxonomy IDs to parse
>> STEP 1: PARSING KRAKEN FILE FOR READIDS 107C_out.kraken
        4.27 million reads processed
        465 read IDs saved
>> STEP 2: READING SEQUENCE FILES AND WRITING READS
        0 read IDs found (4.27 mill reads processed)
        0 reads printed to file
        Generated file: extract_107C.fastq
PROGRAM END TIME: 08-07-2020 01:40:44

[1]+  Done                    python extract_kraken_reads.py -k 107C_out.kraken -s 107C_seq.file -o extract_107C.fastq -t 813

Any comments would be appreciated.

**Comment by jenniferlu717** [comment]
I had made some modifications about what the script is looking for with regard to the read IDs.

Can you show me the first three lines of the Kraken report and of the sequence file?

**Comment by jvhagey** [comment]
Hi @jenniferlu717, thanks for making these! I'm running into the same hiccup. This is my command (I just removed the paths so its readable). 

```
python extract_kraken_reads.py --include-children --taxid 5806 -s 40236_Calf_L001_kneaddata_paired_1.fastq -s2 40236_Calf_L001_kneaddata_paired_2.fastq -o 40236_Calf_L001_kneaddata_paired_Kclean_1.fastq -o2 40236_Calf_L001_kneaddata_paired_Kclean_2.fastq --report 40236_Calf_report.txt -k 40236_Calf.kraken
```

```
PROGRAM START TIME: 11-17-2020 22:18:16
>> STEP 0: PARSING REPORT FILE /scicomp/home/qpk9/QC/Kraken/40236_Calf_report.txt
        3 taxonomy IDs to parse
>> STEP 1: PARSING KRAKEN FILE FOR READIDS /scicomp/home/qpk9/QC/Kraken/40236_Calf.kraken
        2.24 million reads processed
        141429 read IDs saved
>> STEP 2: READING SEQUENCE FILES AND WRITING READS
        0 read IDs found (2.24 mill reads processed)
        0 read IDs found (2.24 mill reads processed)
        0 reads printed to file
        Generated file: 40236_Calf_L001_kneaddata_paired_Kclean_1.fastq
        Generated file: 40236_Calf_L001_kneaddata_paired_Kclean_2.fastq
PROGRAM END TIME: 11-17-2020 22:20:02
```
So It looks like it found sequences I want they just don't get written for some reason. Let me know if I am doing something wrong. Happy to help debug.

**Comment by jvhagey** [comment]
Found the problem:

There was a #0 on the end of sequences in the `test_id` variable that didn't match the keys in the `save_readids` dictionary. I added `or test_id.endswith("#0"):` to the end of lines 362 and 396 so it reads ` if ("/1" in test_id) or ("/2" in test_id) or test_id.endswith("#0"):`  and that fixed the problem. Hope this helps someone in the future. Thanks for the script!!

**Comment by jenniferlu717** [comment]
I'm glad that you were able to solve the problem.

Apologies for that error. It was hard for me to adjust the script to every type of paired readid formats.
