### ISSUE TITLE
extract_kraken_reads wrong number of reads, blast result does not match

### ISSUE THREAD

**Issue by pe-se** [jenniferlu717/KrakenTools#18]
Hi, 
I tried with several different taxa to extract reads from a kraken file - first, the number of extracted reads does not match (e.g. 11 reads assigned to species in kraken file, but only 3 are extracted), and second, if I blast these sequences, they are in almost all cases nowhere near what kraken assigned them to (with a complete nt-kraken-database), like I sometimes get bacteria or plants, when it should be a mammal (for very few taxa though the blast result matches the kraken assignment).

I used 
krakentools/extract_kraken_reads.py -k sample1.kraken -s sample1.fastq -t 37349 -o test.fasta

the process looks like this

PROGRAM START TIME: 08-18-2020 09:42:54
	1 taxonomy IDs to parse
>> STEP 1: PARSING KRAKEN FILE FOR READIDS t1_trim.kraken
	0.61 million reads processed
	9 read IDs saved
>> STEP 2: READING SEQUENCE FILES AND WRITING READS
	4 read IDs found (0.61 mill reads processed)
	0 reads printed to file
	Generated file: extr_trest.fasta

and the output file contains only **3** sequences of the 9 directly assigned reads, which when blasted are nothing close to the assigned taxon...

I am very confused about these results and any advice would be greatly appreciated.

**Comment by jenniferlu717** [comment]
How large are you files? Can you send me the read file and the Kraken output file? (jennifer.lu717@gmail.com

**Comment by jenniferlu717** [comment]
Fixed this issue offline so I will close this for now.
