### ISSUE TITLE
kreport2krona.py not working properly in default mode

### ISSUE THREAD

**Issue by rizkg** [jenniferlu717/KrakenTools#2]
The default mode of kreport2krona.py is not "--intermediate-ranks" as indicated, by default it only outputs standard ranks.
When outputting std ranks only it seems that the non-standard ranks are simple erased, which results in wrong krona report.
For example when I have something like this in the kraken2 report
 ```
 1.96	74140	0	S	4932	                          Saccharomyces cerevisiae
  1.96	74140	74140	S1	559292	                            Saccharomyces cerevisiae S288C
```
Then kreport2krona.py will compute cerevisiae = 0 and it will therefore not show in the graph, whereas I expected the non standard rank S1 to be included in its parent node S.

**Comment by jenniferlu717** [comment]
Thanks for noticing this. Working on a fix.

**Comment by jenniferlu717** [comment]
Fixed in the most recent github version. Let me know if you continue to notice problems!
