### ISSUE TITLE
Format of output files from extract_kraken_reads.py

### ISSUE THREAD

**Issue by cgh19** [jenniferlu717/KrakenTools#20]
Hi,
I use extract_kraken_reads.py to separate reads depending on the taxonomy ID. My input files are fastq paired read files and I was hoping that the extracted files would also be fastq files, but it looks like there are fasta files. Is there an option to get fastq files as an output?
Thanks!

**Comment by jenniferlu717** [comment]
--fastq-output is the option you want to add

**Comment by cgh19** [comment]
Thanks and sorry, just realised that it was an overlook on my part (clearly explained in the instructions)!

**Comment by jenniferlu717** [comment]
No worries, glad to help :)
