### ISSUE TITLE
Error occurs in <make_kreport.py>

### ISSUE THREAD

**Issue by wyanren** [jenniferlu717/KrakenTools#29]
Hi Jennifer,
i meet an error report in the <make_kreport.py>, i wonder why it happens.
Here is my Log:

`
-bash-4.2$ python ~/yanren/app/KrakenTools-master/make_kreport.py -i MT1.krak2 -t ~/MY_KRAKEN2_DATABASE/TAXONOMY_MAKE.txt -o report
PROGRAM START TIME: 12-19-2020 12:49:03
>> STEP 1/4: Reading taxonomy /lustre/quanzx/MY_KRAKEN2_DATABASE/TAXONOMY_MAKE.txt...
	30392 nodes saved
>> STEP 2/4: Reading kraken file MT1.krak2...
	204.704 million reads processed
>> STEP 3/4: Creating final tree...
Traceback (most recent call last):
  File "/lustre/quanzx/yanren/app/KrakenTools-master/make_kreport.py", line 198, in <module>
    main()
  File "/lustre/quanzx/yanren/app/KrakenTools-master/make_kreport.py", line 145, in main
    p_node = taxid2node[curr_tid].parent 
KeyError: 'Yuavirus (taxid 1299429)'
`

**Comment by jenniferlu717** [comment]
Dont use "--use-names" when running kraken2 - the make_kreport script is not compatible with those outputs
