### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by biofuture** [jenniferlu717/KrakenTools#3]
Hi, 

Thanks for developing this scripts to post-process Kraken result.  Can I use it to process the KrakenUniq report?  

I try your script to combine multi-report.  It reports the above error. Can you help to figure out what 's wrong with my running?  

perl ../KrakenTools/combine_kreports.py -r SLX_14_S5.fastp.clean.report SLX_15_S40.fastp.clean.report -o ../test.out.report 
>>STEP 1: READING REPORTS
	1/2 samples processedTraceback (most recent call last):
  File "../KrakenTools/combine_kreports.py", line 309, in <module>
    main()
  File "../KrakenTools/combine_kreports.py", line 201, in main
    report_vals = process_kraken_report(line)
  File "../KrakenTools/combine_kreports.py", line 113, in process_kraken_report
    int(split_str[1])
IndexError: list index out of range

**Comment by MADscientist314** [comment]
I am having the same issue.  I also tried this with mpa-style reports and received the same error

**Comment by jenniferlu717** [comment]
Sorry for not responding. I will try to debug the code and have a solution by next Monday.

@MADscientist314  The code doesnt work on the mpa style output at the moment but should work on the Kraken 1/2 report output. I havent tested on KrakenUniq reports.

**Comment by MADscientist314** [comment]
Thank so much for responding.  I was able to get the combine script to work by rerunning the outputs from krakenuniq and using the new reports for combining.

**Comment by jenniferlu717** [comment]
The script doesn't run on perl, its a python script. Also added another error catch in the script so it should work now.
