### ISSUE TITLE
error with "combine_mpa.py" script

### ISSUE THREAD

**Issue by mars188** [jenniferlu717/KrakenTools#37]
Hi

Your script will be very useful for me if you could please help me with the following problem:

I have 206 samples generated through kraken2 (kreport) with --mpa style. When I try to combine them with your script, it gives me the following error:
Here is my script:
`combine_mpa.py -i file1 file2 file3 filen -o output.txt `
and here is the error:
`Number of files to parse: 6
Traceback (most recent call last):
  File "../KrakenTools/combine_mpa.py", line 142, in <module>
    main()
  File "../KrakenTools/combine_mpa.py", line 83, in main
    [classification, val] = line.strip().split('\t')
ValueError: need more than 1 value to unpack`

Interestingly, if I combine 2 or 3 files with the same script, it works perfectly fine. 

Please let me know what changes I should make to make it work? Many thanks in advance.

**Comment by mars188** [comment]
I was able to solve this issue.. actually this error occurs only when input kreport files are not properly sorted. They must be sorted in a similar way in order to successfully run this code.

**Comment by emilynyeo** [comment]
@mars188 what do you mean by "sorted"? I think I am now running into the same issue :)
