### ISSUE TITLE
The error when running extract_kraken_reads.py

### ISSUE THREAD

**Issue by minsookim1983** [jenniferlu717/KrakenTools#4]
Hello,

I got an error from running the command "extract_kraken_reads.py" as below:
=========================================================================
PROGRAM START TIME: 11-26-2019 02:26:33
>> STEP 0: PARSING REPORT FILE food.virome/kraken2.output/nt.output/BVD2.report
Traceback (most recent call last):
  File "KrakenTools-master/extract_kraken_reads.py", line 388, in <module>
    main()
  File "KrakenTools-master/extract_kraken_reads.py", line 192, in main
    report_vals = process_kraken_report(line)
  File "KrakenTools-master/extract_kraken_reads.py", line 110, in process_kraken_report
    int(split_str[1])
NameError: name 'split_str' is not defined
=========================================================================
Please, give me some hint to resolve this problem.
Thank you.

Min-Soo Kim

**Comment by MetaQiime** [comment]
I have the same error...

**Comment by jenniferlu717** [comment]
Sorry, just fixed the script. Let me know if you have any other issues.
