### ISSUE TITLE
extract kraken read _empty fastq file 

### ISSUE THREAD

**Issue by arz19893** [jenniferlu717/KrakenTools#47]
HI , 
I am trying to extract read from kraken file , the fastq file generated seems empty? I am sure with taxID is in Kraken file but not sure where is the mistake ?

![test1](https://user-images.githubusercontent.com/65975305/158666144-e01a3330-57fa-4eff-96a5-1a6e68c63f29.jpg)
)

Thanks for your help (:

**Comment by denise0593** [comment]
Hi, how did you solve the problem? Thank you very much
