### ISSUE TITLE
local variable 'prev_node' referenced before assignment

### ISSUE THREAD

**Issue by SumeetTiwari07** [jenniferlu717/KrakenTools#5]
Hi,
I was trying to extract the reads by the script but its throwing me this error all the time. I tried to figure out the bug but didn't got. Please have a look. The kraken2 was run on the reads

**cmd line: python3 extract_kraken_reads.py -k output.txt -s1 R1.fastq.gz -s2 R2.fastq.gz -t 1 -o R1_c_1.fastq -o2 R2_c_2.fastq -r report.txt --include-children**
STEP: Parsing report file report.txt
Traceback (most recent call last):
  File "extract_kraken_reads.py", line 395, in <module>
    main()
  File "extract_kraken_reads.py", line 206, in main
    while level_num != (prev_node.level_num + 1):
UnboundLocalError: local variable 'prev_node' referenced before assignment

**Comment by jenniferlu717** [comment]
It might be a python3 issue (since I've never experienced this with python 2), but I added in a variable assignment that should help with the problem? Let me know if you still have this error using the newest extract_kraken_reads.py script please.
