### ISSUE TITLE
Latest commit of kraken2mpa.py broke the script due to code that was meant for extract_kraken_reads.py

### ISSUE THREAD

**Issue by simonleandergrimm** [jenniferlu717/KrakenTools#62]
As others have commented, kraken2mpa.py returns the following error message when used:
`
  File "[...]kreport2mpa.py", line 188, in <module>
    main()
  File "[...]kreport2mpa.py", line 143, in main
    report_vals = process_kraken_report(line)
  File "[...]kreport2mpa.py", line 80, in process_kraken_report
    taxid = int(l_vals[-3])
`

After some digging I found the issue. In the latest [commit](https://github.com/jenniferlu717/KrakenTools/commit/91325ceb3a175a32d1b2b734e1448b0542c9b50e), additional code was introduced into kraken2mpa.py, which broke it by introducing an undefined variable called l_lvals.

Funnily enough the variable is defined in `extract_kraken_reads.py`. Thus there was likely a copy and paste error in the latest commit. Using `kreport2mpa.py` before the linked commit makes the script work again.

@jenniferlu717 fixing this should be super easy! Thanks for the tool in general, was exactly what I need.

**Comment by jenniferlu717** [comment]
Apologies, I fixed the issue (I believe)
