### ISSUE TITLE
I would like to check if I can run 'combine_kreports.py' on my Kraken2 reports? 

### ISSUE THREAD

**Issue by Olla10** [jenniferlu717/KrakenTools#67]
Hi 
I would like to check if I can run 'combine_kreports.py' on my Kraken2 reports? I have around 1200 kraken2 reports. It shows below errors when I tried to run it using the following command.

combine_kreports.py -r *.report  -o Kraken2_results_all.report

Could you please advise?

Thanks.

Could you please advise?

 >>STEP 1: READING REPORTS
	1/3 samples processedTraceback (most recent call last):
  File "combine_kreports.py", line 311, in <module>
    main()
  File "combine_kreports.py", line 201, in main
    curr_file = open(r_file,'r')
IsADirectoryError: [Errno 21] Is a directory: '/nfs/wsi/tgm/metagenomic_db/x/kraken2_results/.'
(

Thanks.

Regards,
Alyaa

**Comment by jenniferlu717** [comment]
The command should work but you need to make sure the parameter you're putting for -r is correct

(Are your reports formatted as *.report) 

I believe you emailed me regarding this issue and we were able to resolve it so I am going to close this for now
