### ISSUE TITLE
combine_kreports -- AttributeError: 'int' object has no attribute 'level_num'

### ISSUE THREAD

**Issue by douglas-hoen** [jenniferlu717/KrakenTools#75]
Hi,

I received the following error when running `combine_kreports.py`:

`AttributeError: 'int' object has no attribute 'level_num'
`

The reports that I'm combining were generated from `krakenuniq-1.0.3`. 

Example report file (head):
```
%       reads   taxReads        kmers   dup     cov     taxID   rank    taxName
100     423281123       423281123       17041967260     6.01    NA      0       no rank unclassified
0.001729        7318    0       49279   2.34    5.713e-05       1       no rank root
0.001724        7296    1       48568   2.36    5.675e-05       131567  no rank   cellular organisms
0.001269        5373    20      48523   2.27    5.702e-05       2       superkingdom        Bacteria
0.0006473       2740    18      31715   1.67    6.813e-05       1224    phylum        Proteobacteria
0.0004139       1752    27      24328   1.57    8.709e-05       1236    class           Gammaproteobacteria
0.0002294       971     2       16422   1.57    0.0002252       72274   order             Pseudomonadales
```

Stepping through the code, the issue seems to be that `taxid` was never initialized because the parser indices in `process_kraken_report()` did not match the input. The following change seems to fix the issue (line 121):
```
# level_type = split_str[-3]
# taxid = split_str[-2]
level_type = split_str[-2]
taxid = split_str[-3]
```

Perhaps column order is different in various kraken programs/versions?

NB: I noticed a similar comment in your **Bracken** issues. Related? Perhaps it would be worth doing a sanity check on the column headers or something and issuing a user-friendly error if they do not conform to expectations?

Many thanks for your tools!

**Comment by njohnso6** [comment]
I fixed the issue, I believe by modifying the script. Line 122 taxid = split_str[-2] should be = split_str[-3] because the output format is slightly different.

**Comment by jenniferlu717** [comment]
I fixed the script so it should work for krakenuniq outputs now. Please use the most recent script and let me know if it does not work (reopen if the newest script does not work)
