### ISSUE TITLE
filter_bracken_output.py: Too many arguments in line

### ISSUE THREAD

**Issue by bheimbu** [jenniferlu717/KrakenTools#80]
Hi there,

I'm trying to filter my bracken output files (classified against the whole nt database). In the end, I want to have only bacterial, archaeal, and viral classified reads (I know, I can simply classify against the standard database (yet this would still include human), but the nt database gives me way more hits). I managed to get all necessary taxids, but, as you can imagine, these are a lot of taxids (~800.000). So once I run `filter_bracken_output.py`, it gives me an error: `Too many arguments in line`.
Do I miss here something -- isn't there a workaround like that I can give the taxid of bacteria and all children could be retrieved automatically (like option `--include-children` as mentioned in #60).

Anyway, any help is highly appreciated,

Cheers Bastian

**Comment by bheimbu** [comment]
Hi,

just wanted to let you know that I have found a workaround. I have changed your python script so that it takes a file with taxids (on separate lines). Here is the adjusted python script [filter_bracken.out.py](https://github.com/jenniferlu717/KrakenTools/files/12094647/filter_bracken.out.txt) and an example [taxid list](https://github.com/jenniferlu717/KrakenTools/files/12094694/include_taxids.txt). Call it like this `python filter_bracken_out.py -i input_file.txt -o output_file.txt --include include_taxids.txt`.

Works also with `--exclude`.

Have fun and cheers,

@bheimbu

**Comment by jenniferlu717** [comment]
Awesome, glad you were able to figure that out.

Sincerely,
Jen Lu
