### ISSUE TITLE
extracting reads with quality values

### ISSUE THREAD

**Issue by rajaldebnath** [jenniferlu717/KrakenTools#9]
Dear Jen
I want to extract the viral reads with --include-children or exclude viral reads with --include children and obtain only the reads for further assembly. How can I get the fastq files rather than fasta files.

Thanks

**Comment by ArnonMe** [comment]
Same question 👍

**Comment by jenniferlu717** [comment]
The script doesnt allow for that right now but I can quickly add an option for that. I should have something that works in the next day

**Comment by jenniferlu717** [comment]
I've added an option for this in the script (--fastq-output), but to do so, I had to remove the option for adding a delimiter inbetween paired reads.

However, users can still output the reads into two output files matching the two pairs so that should be fine.

**Comment by rajaldebnath** [comment]
Sorry Jen for being late in replying. Thanks!! I could extract the filtered fastq files.
